### ISSUE TITLE
Cannot read property 'endpoints' of undefined

### ISSUE THREAD

**Issue by umaar** [gosquared/node-gosquared#3]
I have some sample code as follows:

```
var GoSquared = require('gosquared');

var gosquared = new GoSquared({
  api_key: 'key',
  site_token: 'token'
});

gosquared.storeEvent('Test Event', {
        'hello': 'world'
    },
    function(e, res){
        if(e) return console.log(e);
        console.log(res);
    }
);
```

which when run using Node gives the error:

```
node_modules/gosquared/lib/gosquared.js:182
  this._exec(this.config.endpoints.data, '/event?' + queryString.stringify(qsP
                        ^
TypeError: Cannot read property 'endpoints' of undefined
    at GoSquared.storeEvent (node_modules/gosquared/lib/gosquared.js:182:25)
```

**Comment by dharini08** [comment]
I got the same issue while using endpoint to run amazon gamelift  locally... whats the solution of it?
my error is " s3.defineService.endpoint.hostname ='http://localhost:8080';
                 ^
TypeError: Cannot read property 'endpoint' of undefined
    at Object.<anonymous>"

**Comment by jbt** [comment]
Hi @dharini08, it looks like you might be in the wrong place - the error message you're coming across is the same as in this issue, but this module has nothing to do with AWS or GameLift I'm afraid.

You're probably looking for the [aws-sdk-js](https://github.com/aws/aws-sdk-js) project or its associated [documentation and developer guides](https://aws.amazon.com/sdk-for-node-js/). I hope that helps!

**Comment by dharini08** [comment]
Thanks you so much.
